### PR TITLE
typo check

### PR DESCRIPTION
**Pull request by htc502**
Hi, sorry for the .last function change... 
I have reverted my branch and pull request now with only typo checks..

### CODE REVIEW

**Comment by dwinter** [comment]
Merged thanks!

How can I credit you for your contribution? If you are OK with publicaly sharing your name/email I can add you to the package as a contributor,

```
person("First", "Last", role=c("ctb"),   email = "account@mail.com")
```

If you'd rather stay under the radar  I can include your GH handle in the acknowledgements of the paper I'll write for this package?

**Comment by htc502** [comment]
glad to be merged.
person(“han”,“guangchun”, role=c(“ctb”),email=“hanguangchun@gmail.com”)
besides,i am interested in eutils related projects as i have to convert ids frequently.  i wrote an excel plugin to do id convertion using eutils. it，s my first time to collabrate with guys working on r package dev. many things to learn...  thinking about adding examples for id convertion and snp annotation, don't know if it is already in your schedue.

**Comment by dwinter** [comment]
[You're in](https://github.com/ropensci/rentrez/commit/8368f6ba729aa3ef0061132fbb0355e772468173) :smile: 

I want to add some "simple" id-conversion examples to the vignette (see #28). I think I will re-write a lot of the vignette, so if you wanted to work on that it might more sense to start a new file (either in `/vignettes` or seperate from the repo for now). 

I don't want to dissuade you from using `rentrez`, but you might also find `biomaRt` helpful for this.

**Comment by htc502** [comment]
thanks for the suggestion. I'll have a try.

**Pull request merged**
